### ISSUE TITLE
Folder rename problem

### ISSUE THREAD

**Issue by segadora** [omarabid/Self-Hosted-WordPress-Plugin-repository#13]
After updating a plugin the plugin changes name from "plugin" to "plugin-48HxJa" do you have any idea, why this is happening?

**Comment by luizbills** [comment]
probably "plugin-48HxJa" is the name of the folder in the zip

**Comment by omarabid** [comment]
Does it deactivate the plugin?

**Comment by segadora** [comment]
I figured out the problem, i didn't create a sub folder in the plugin

**Comment by omarabid** [comment]
Could explain better what you mean by "didn't create a sub folder in the plugin". Just in case someone else runs into the same issue.

**Comment by segadora** [comment]
/plugin.php

Should be

/plugin/plugin.php
Den 13. jul. 2016 6.33 PM skrev "Abid Omar" <notifications@github.com>:

**Comment by segadora** [comment]
We had an old wordpress installation with automated plugins creation, and it was not upgraded since wordpress 3. So just follow the documentation and it will work https://developer.wordpress.org/plugins/the-basics/best-practices/
