### ISSUE TITLE
small bug in example 'update.php'

### ISSUE THREAD

**Issue by Dipzaus** [omarabid/Self-Hosted-WordPress-Plugin-repository#20]
When the class checks for update, it calls the case 'version'.
This case needs the obj->tested, but that is only defined in the case 'info'.

I solved this by adding the obj->tested to the list of standards, just below obj->new_version.

**Comment by omarabid** [comment]
Can you fix this in a pull request?

**Comment by enri90** [comment]
Replace

echo json_encode( $obj );
