### ISSUE TITLE
prevent other plugins to update

### ISSUE THREAD

**Issue by DediData** [omarabid/Self-Hosted-WordPress-Plugin-repository#21]
Hi,
Thank you for your great code, It is really helpful
But does it prevent other plugins to be check for new updates?

Regards

**Comment by omarabid** [comment]
Why do you want to prevent other plugins from updating? Or are you saying that it does prevent other plugins from updating?

**Comment by parsmizban** [comment]
Hi,
I got my answer, Actually I modified your script to auto update themes
I think something should be change to use json_encode and decode, and use arrays instead of stdClass
Thank you very much
