### ISSUE TITLE
after update the plugin become deactivated  

### ISSUE THREAD

**Issue by AlaaSelim** [omarabid/Self-Hosted-WordPress-Plugin-repository#6]
after update the plugin become deactivated  and i have to activate it manually any solution for that?

**Comment by omarabid** [comment]
@AlaaSelim Do you mean updating the WordPress installation?

**Comment by AlaaSelim** [comment]
@omarabid hi thanks a lot for your reply,  i mean after the plugin update, it become deactivated and WordPress say can't find the plugin, but the new update is installed  i just have to activate it manually. 

it seem that WordPress install the plugin update in new random path like randompath1256/plugin.php instead of plugin/plugin.php

I ended up using a different approach to update my plugin from my site instead of WordPress repository.

**Comment by mjperales** [comment]
I had the same problem but it was because I tried to zip the file with the version number at the end. So when it was unzip it kept that name instead of the plugin name. Anyway, once I fixed this issue everything worked perfectly. Thanks for the tutorial!

**Comment by kluverp** [comment]
Yes, be sure to name the *.zip file the same as the plugin name. Also be sure to have a folder inside the *.zip file with the same name as the plugin name. Do not put the plugin files in the root of the *.zip file, or it won't work.

**Comment by omarabid** [comment]
If anyone wants to contribute a small Readme file, I'll be glad to merge it. The article on Tuts is very old now and very unlikely to get updated.

**Comment by kluverp** [comment]
I will try to add a readme file...

**Comment by omarabid** [comment]
@kluverp Thank you. I appreciate the effort.
