### ISSUE TITLE
Update class name

### ISSUE THREAD

**Issue by mjperales** [omarabid/Self-Hosted-WordPress-Plugin-repository#7]
Hi,
I just wanted to note that the plugin.php file needs to be updated with the correct class name. The class name is WP_AutoUpdate and in the plugin.php file it is called wp_auto_update.

**Comment by omarabid** [comment]
@mjperales 
If you open a PR for it, I'll merge it.

**Comment by omarabid** [comment]
@mjperales Thank you!
