### ISSUE TITLE
getRemote_version, getRemoteInformation and getRemote_license

### ISSUE THREAD

**Issue by kluverp** [omarabid/Self-Hosted-WordPress-Plugin-repository#8]
The way I see it, these functions are the same. Maybe you can simplify the class by removing two of the functions and add the action as a parameter to a single function?

**Comment by omarabid** [comment]
@kluverp makes sense. If you are interested in fixing, make a PR and I'll merge it.

**Comment by omarabid** [comment]
@kluverp Thank you!
